openapi: 3.0.0
paths:
  /bulk/md5:
    post:
      responses:
        '200':
          description: Success
        '404':
          description: >-
            JSON format incorrect. An array of hashes in the key 'hashes' is
            expected.
      description: Bulk search of MD5 hashes in a JSON array with the key 'hashes'.
      operationId: post_bulkmd5
      tags:
        - default
  /bulk/sha1:
    post:
      responses:
        '200':
          description: Success
        '404':
          description: >-
            JSON format incorrect. An array of hashes in the key 'hashes' is
            expected.
      description: Bulk search of SHA1 hashes in a JSON array with the 'hashes'.
      operationId: post_bulksha1
      tags:
        - default
  /children/{sha1}/{count}/{cursor}:
    parameters:
      - name: sha1
        in: path
        required: true
        schema:
          type: string
      - name: count
        in: path
        required: true
        schema:
          type: integer
      - name: cursor
        in: path
        required: true
        schema:
          type: string
    get:
      responses:
        '200':
          description: Success
        '400':
          description: SHA1 value incorrect, expecting a SHA1 value in hex format
        '404':
          description: The SHA1 value has no known child.
      description: >-
        Return children from a given SHA1.  A number of element to return and an
        offset must be given. If not set it will be the 100 first elements. A
        cursor must be given to paginate over. The starting cursor is 0.
      operationId: get_children
      tags:
        - default
  /info:
    get:
      responses:
        '200':
          description: Success
      description: Info about the hashlookup database
      operationId: get_info
      tags:
        - default
  /lookup/md5/{md5}:
    parameters:
      - name: md5
        in: path
        required: true
        schema:
          type: string
    get:
      responses:
        '200':
          description: Success
        '400':
          description: MD5 value incorrect, expecting a MD5 value in hex format
        '404':
          description: Non existing MD5
      description: Lookup MD5.
      operationId: get_lookup_md5
      tags:
        - default
  /lookup/sha1/{sha1}:
    parameters:
      - name: sha1
        in: path
        required: true
        schema:
          type: string
    get:
      responses:
        '200':
          description: Success
        '400':
          description: SHA1 value incorrect, expecting a SHA1 value in hex format
        '404':
          description: Non existing SHA1
      description: Lookup SHA-1.
      operationId: get_lookup_sha1
      tags:
        - default
  /lookup/sha256/{sha256}:
    parameters:
      - name: sha256
        in: path
        required: true
        schema:
          type: string
    get:
      responses:
        '200':
          description: Success
        '400':
          description: SHA-256 value incorrect, expecting a SHA-256 value in hex format
        '404':
          description: Non existing SHA-256
      description: Lookup SHA-256.
      operationId: get_lookup_sha256
      tags:
        - default
  /parents/{sha1}/{count}/{cursor}:
    parameters:
      - name: sha1
        in: path
        required: true
        schema:
          type: string
      - name: count
        in: path
        required: true
        schema:
          type: integer
      - name: cursor
        in: path
        required: true
        schema:
          type: string
    get:
      responses:
        '200':
          description: Success
        '400':
          description: SHA1 value incorrect, expecting a SHA1 value in hex format
        '404':
          description: The SHA1 value has no known parent.
      description: >-
        Return parents from a given SHA1. A number of element to return and an
        offset must be given. If not set it will be the 100 first elements. A
        cursor must be given to paginate over. The starting cursor is 0.
      operationId: get_parents
      tags:
        - default
  /session/create/{name}:
    parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
    get:
      responses:
        '200':
          description: Success
        '400':
          description: Expecting a name for the session
        '500':
          description: Session feature is not enabled
      description: >-
        Create a session key to keep search context. The session is attached to
        a name. After the session is created, the header `hashlookup_session`
        can be set to the session name.
      operationId: get_session_create
      tags:
        - default
  /session/get/{name}:
    parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
    get:
      responses:
        '200':
          description: Success
        '400':
          description: Expecting a name for the session
        '500':
          description: Session feature is not enabled
      description: Return set of matching and non-matching hashes from a session.
      operationId: get_session_matches
      tags:
        - default
  /stats/top:
    get:
      responses:
        '200':
          description: Success
        '400':
          description: Public statistics not enabled
      description: Return the top 100 of most queried values.
      operationId: get_stattop
      tags:
        - default
info:
  title: hashlookup CIRCL API
  version: 1.2-oas3
  description: "Hash Lookup is a public API to lookup hash values against known database of file.
    The files include,\n
    Common Windows 10 and Windows 11 build (French, Dutch, German, UK, US).\n
    NIST NSRL - All RDS hash sets including current, modern, android, iOS and legacy + SHA256 mapping.\n
   Ubuntu packages distribution.\n
   CentOS core OS distribution.\n
   Fedora project EPEL repository.\n
   Kali linux packages distribution.\n
   OpenSUSE distribution packages.\n
   OpenBSD binary tar.gz distribution.\n
   CDNJS.\n
   Snap public repository."
  license:
    name: CC-BY
tags:
  - name: default
    description: Default namespace
servers:
  - url: https://hashlookup.circl.lu
components:
  responses:
    ParseError:
      description: When a mask can't be parsed
    MaskError:
      description: When any error occurs on mask